services:
  dlt-booth:
    build: !reset null
    image: ghcr.io/sedimark/dlt-booth:dev
    networks: !override
      - sedimark_shared
      - dlt-booth-net
    profiles: !reset null
    env_file: !reset null
    environment:
      RUST_LOG: ${DLT_RUST_LOG:-info}
      RUST_BACKTRACE: ${DLT_RUST_BACKTRACE:-1}
      HOST_ADDRESS: ${DLT_HOST_ADDRES:-0.0.0.0}
      HOST_PORT: ${DLT_HOST_ADDRES:-8085}
      NODE_URL: ${DLT_NODE_URL}
      FAUCET_API_ENDPOINT: ${DLT_FAUCET_API_ENDPOINT}
      RPC_PROVIDER: ${DLT_RPC_PROVIDER}
      CHAIN_ID: ${DLT_CHAIN_ID}
      ISSUER_URL: ${DLT_ISSUER_URL}
      KEY_STORAGE_STRONGHOLD_SNAPSHOT_PATH: ${DLT_KEY_STORAGE_STRONGHOLD_SNAPSHOT_PATH}
      KEY_STORAGE_STRONGHOLD_PASSWORD: ${DLT_KEY_STORAGE_STRONGHOLD_PASSWORD}
      WALLET_STRONGHOLD_SNAPSHOT_PATH: ${DLT_WALLET_STRONGHOLD_SNAPSHOT_PATH}
      WALLET_STRONGHOLD_PASSWORD: ${DLT_WALLET_STRONGHOLD_PASSWORD}
      DB_USER: ${DLT_BOOTH_DB_USER:-postgres}
      DB_PASSWORD: ${DLT_BOOTH_DB_PASSWORD:-dlt_booth}
      DB_NAME: dlt_booth
      DB_HOST: "postgres" # "postgres" for deploying, "127.0.0.1 " for dev
      DB_PORT: 5432
      DB_MAX_POOL_SIZE: 16

  postgres:
    profiles: !reset null
    environment: !override
      POSTGRES_USER: ${DLT_BOOTH_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DLT_BOOTH_DB_PASSWORD:-dlt_booth}
      POSTGRES_DB: dlt_booth

networks:
  dlt-booth-net:
    driver: bridge
