services:
  marketplace:
    image: ghcr.io/sedimark/marketplace-frontend:development
    container_name: marketplace-frontend
    ports:
      - "3000:3000"
    networks:
      - sedimark_shared
    environment:
      - NODE_ENV=production
      - BATCH_SIZE=10
      - CATALOGUE_URL=http://catalogue:3030
      - RECOMMENDER_URL=http://recommender:8000
      - DLT_BOOTH_URL=http://dlt-booth:8085
      - BROKER_URL=http://api-gateway:8080

  catalogue:
    image: stain/jena-fuseki:latest
    container_name: catalogue
    ports:
      - "3030:3030"
    volumes:
      - catalogue_data:/fuseki
    networks:
      - sedimark_shared
    environment:
      - ADMIN_PASSWORD=admin

  recommender:
    image: ghcr.io/sedimark/recommender:dev
    container_name: recommender
    ports:
      - "8000:8000"
    volumes:
      - recommender_data:/data/db
    networks:
      - sedimark_shared
    environment:
      - CATALOGUE_URL=http://catalogue:3030

volumes:
  catalogue_data:
  recommender_data:

networks:
  sedimark_shared:
    driver: bridge
