include:
  - path:
      - ./dlt-booth.yaml

services:
  marketplace:
    image: ghcr.io/sedimark/marketplace-frontend/marketplace-frontend:development
    container_name: marketplace-frontend
    ports:
      - "3001:3000"
    networks:
      - sedimark_shared
    environment:
      - NODE_ENV=production
      - BATCH_SIZE=${MARKETPLACE_BATCH_SIZE}
      - CATALOGUE_URL=${MARKETPLACE_CATALOGUE_URL}
      - RECOMMENDER_URL=http://recommender:8001
      - DLT_BOOTH_URL=http://dlt-booth:8085
      - BROKER_URL=http://api-gateway:8080

  profile:
    image: ghcr.io/sedimark/profile:latest
    container_name: profile
    ports:
      - "3005:3005"
    networks:
      - sedimark_shared
    environment:
      - API_KEY=${PROFILE_API_KEY}
    volumes:
      - profile_server_data:/app/data

  recommender:
    image: ghcr.io/sedimark/recommender:dev
    container_name: recommender
    ports:
      - "8001:8000"
    volumes:
      - recommender_data:/data/db
    networks:
      - sedimark_shared
    environment:
      - CATALOGUE_URL=${MARKETPLACE_CATALOGUE_URL}

volumes:
  profile_server_data:
  recommender_data:

networks:
  sedimark_shared:
    driver: bridge
